### ISSUE TITLE
SBT 1.3.0 causes resolution errors with 0.18

### ISSUE THREAD

**Issue by coltfred** [frugalmechanic/fm-sbt-s3-resolver#58]
After updating to sbt 1.3.0 the resolver didn't work. If you turn off coursier, it seems to work again.

Adding `ThisBuild / useCoursier := false` to the build is what I did.

For clarity, I have an s3 resolver like so `resolvers += "ICL S3".at("s3://maven.XXXXXXXXXX.com/releases")`  which works on sbt 1.2.8, but not 1.3.0. Not sure if something needs to change in here or if it's a bug in SBT. 

cc/ @eed3si9n

**Comment by tpunder** [comment]
Yup, I ran into this when I tried to upgrade my projects to sbt 1.3.0 and need to look into it.  It appears to be partially working in the sense that I see S3 Clients being created and it seems like it is maybe downloading stuff from S3 but I'm seeing some "No modified time in response" messages.  So perhaps additional support in https://github.com/frugalmechanic/fm-sbt-s3-resolver/blob/master/src/main/scala/fm/sbt/s3/S3URLConnection.scala needs to be added to make Coursier happy.

**Comment by tpunder** [comment]
It also looks like maybe there is a new (at least to me) way to plugin new protocols to Coursier: 

https://github.com/coursier/coursier/blob/46ad7243bea71e56dbda6df133a328535ac4c61e/modules/cache/jvm/src/main/scala/coursier/cache/CacheUrl.scala#L26-L32

So that's probably worth investigating too.

**Comment by tpunder** [comment]
More info:

SBT 1.3.0 seems to download the pom files just fine from S3 but then I see stuff like:

```
checksum format error: /Users/tim/Library/Caches/Coursier/v1/s3/maven.example.com/releases/com/example/my-lib_2.12/0.79.0/.my-lib_2.12-0.79.0.pom__sha1
```

In my `/Users/tim/Library/Caches/Coursier/v1/s3/maven.example.com/releases/com/example/my-lib_2.12/0.79.0` directory I see:

```
-rw-r--r-- 1 tim staff    0 Sep  5 17:02 .my-lib_2.12-0.79.0.pom.checked
-rw-r--r-- 1 tim staff    0 Sep  3 10:37 .my-lib_2.12-0.79.0.pom__md5
-rw-r--r-- 1 tim staff    0 Sep  3 10:37 .my-lib_2.12-0.79.0.pom__sha1
-rw-r--r-- 1 tim staff    0 Sep  3 10:37 .my-lib_2.12-0.79.0.pom__sha256
-rw-r--r-- 1 tim staff 5046 Sep  3 10:37 my-lib_2.12-0.79.0.pom
```
Note the 0 length files.

**Comment by tpunder** [comment]
@coltfred After much debugging I found and fixed some bugs that were preventing Coursier in SBT 1.3 to work via commit https://github.com/frugalmechanic/fm-sbt-s3-resolver/commit/5f6520ef7bf145f33159b47c2fed906250fb1376

I've published version 0.19.0 which contains the fix:

```
addSbtPlugin("com.frugalmechanic" % "fm-sbt-s3-resolver" % "0.19.0")
```

**Comment by coltfred** [comment]
0.19.0 seems to be working with Coursier. Thank you so much!

**Comment by erdeszt** [comment]
I still see this issue with `0.19.0`
I get a `checksum format error` and the checksum files are empty (0 length) in the Ivy cache folder.

**Comment by tpunder** [comment]
@erdeszt Here are a few things to try:

- Delete the cache directories for any dependencies coming from S3 (to clear out the 0 length files)
- Delete the `project/project` and `project/target` directories in your project.  I ran into an issue where SBT did not pickup the latest version of the plugin unless I deleted those directories and let SBT re-build them.

**Comment by erdeszt** [comment]
@tpunder thanks, that solved it!
